# Generated by Django 5.0.2 on 2024-06-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goal_setting_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="due_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="target_datetime",
            field=models.DateTimeField(),
        ),
    ]
